version: 2

project_name: guppy

builds:
  - id: guppy
    main: ./
    binary: guppy
    ldflags:
      # Sets the version variable in the build package to the build version prefixed with a 'v'
      # Sets the main.date to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
      - -s -w -X github.com/storacha/guppy/pkg/build.version=v{{.Version}} -X github.com/storacha/guppy/pkg/build.Commit={{.Commit}} -X github.com/storacha/guppy/pkg/build.Date={{.CommitDate}} -X github.com/storacha/guppy/pkg/build.BuiltBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 'amd64'
      - 'arm64'
    # Change to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
    mod_timestamp: '{{.CommitTimestamp}}'
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

archives:
  - formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      guppy_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: darwin
        formats:
          - zip

changelog:
  disable: true
