FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*
COPY guppy /usr/bin/guppy
ENTRYPOINT ["/usr/bin/guppy"]
